version: "3.7"

services:
  rabbitmq1:
    build: rabbitmq/.
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq-custom
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,debug}]}] -setcookie clusterCookieSecretRnJpIEp1bCAyMyAxMjoxMDoyNiBQTSBFQVQgMjAyMQo=
      - RABBITMQ_NODENAME=rabbit@rabbitmq1

    ports:
      - "8600:5672"
      - "18600:15672"
    networks:
      - ha-messaging


networks:
   ha-messaging:
      external: true
